project:
  title: "TEC-IN2039 Data Visualization for Decision Making"
  type: website
  output-dir: docs
editor: visual

website:
  title: "IN2039 Data Visualization for Decision Making"
  page-navigation: true
  sidebar:
    contents:
      - href: TEC-IN2039-EN-index.qmd
        text: Home

author: 
  - name: Alan R. Vazquez
    affiliations:
      - name: Department of Industrial Engineering
        
format:
  html:
    toc: true
    shift-heading-level-by: 1

  revealjs:
    output-ext: "slides.html"
    chalkboard: true
    multiplex: true
    footer: "Tecnologico de Monterrey"
    logo: IN2039_logo.png
    css: style.css
    slide-number: True


